apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/name: grafana
    product: monitoring
    customer: acme-corp
    version: "10.0.0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.8
    helm:
      parameters:
        - name: replicas
          value: "1"
        - name: resources.requests.cpu
          value: "100m"
        - name: resources.requests.memory
          value: "128Mi"
        - name: persistence.enabled
          value: "false"
        - name: adminPassword
          value: "admin123"
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
