apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-product-subscriptions
  namespace: argocd
  labels:
    app.kubernetes.io/name: customer-product-subscriptions
    type: subscription-based
spec:
  generators:
    - matrix:
        generators:
          # Get customer metadata
          - git:
              repoURL: http://172.27.161.37:7990/scm/test/customer-configs.git
              revision: main
              files:
                - path: customers/*/products.yaml
          # This assumes products.yaml contains a list like:
          # customer: customer-01
          # products:
          #   - name: product-a
          #     enabled: true
          #   - name: product-b
          #     enabled: true
  template:
    metadata:
      name: '{{customer}}-{{products.name}}'
      labels:
        customer: '{{customer}}'
        product: '{{products.name}}'
        enabled: '{{products.enabled}}'
    spec:
      project: default
      sources:
        - repoURL: http://172.27.161.37:7990/scm/test/platform-infrastructure.git
          targetRevision: main
          path: products/{{products.name}}
          helm:
            valueFiles:
              - $values/products/{{products.name}}/base-values.yaml
              - $values/products/{{products.name}}/customers/{{customer}}.yaml
        - repoURL: http://172.27.161.37:7990/scm/test/customer-configs.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{customer}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      # Only sync if product is enabled for this customer
      syncPolicy:
        automated:
          prune: '{{products.enabled}}'
          selfHeal: '{{products.enabled}}'
